package com.mor.itas.planning.domain.event;

public enum EventType {
    ANNUAL_AUDIT_PLAN_CREATED,
    ANNUAL_AUDIT_PLAN_APPROVED,
    AUDIT_CASE_CREATED,
    AUDIT_REFERRAL_RECEIVED,
    AUDIT_CASE_SELECTED,
    RANDOM_AUDIT_CASE_SELECTED,
    TREATMENT_PLAN_ATTACHED,
    AUDIT_CASE_ASSIGNED,
    AUDIT_CASE_REASSIGNED
}
